[package]
name = "tg-rcore-tutorial-user-T3L3"
description = "User-space apps for ch3-T3L3: ASCII snake game with polling and interrupt-style control."
version = "0.0.1-preview.4"
edition = "2024"
authors = ["Feiran Qin <qfr23@mails.tsinghua.edu.cn>"]
repository = "https://github.com/os-biglab/tg-rcore-tutorial-user-T3L3"
homepage = "https://github.com/os-biglab/tg-rcore-tutorial-user-T3L3/tree/test"
documentation = "https://github.com/os-biglab/tg-rcore-tutorial-user-T3L3/tree/test/docs"
license = "GPL-3.0"
readme = "README.md"
keywords = ["ai","ai4ose","kernel","learning","os"]
categories = ["no-std", "embedded"]

[lib]
name = "user_lib"
path = "src/lib.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
tg-console = { package = "tg-rcore-tutorial-console", version = "0.4.8" }
tg-syscall = { package = "tg-rcore-tutorial-syscall", version = "0.4.8", features = ["user"] }
customizable-buddy = "0.0.2"

[workspace]
