[ch3]
base = 0x8100_0000
step = 0x0020_0000
cases = [
    "snake",
]

[ch3_exercise]
base = 0x8100_0000
step = 0x0020_0000
cases = [
    "snake",
]

[ch4]
cases = [
    "tetris",
]

[ch4_exercise]
cases = [
    "tetris",
]

[ch5]
cases = [
    "initproc",
    "user_shell",
    "pingpong",
]

[ch5_exercise]
cases = [
    "initproc",
    "user_shell",
    "pingpong",
]

[ch6]
cases = [
    "initproc",
    "user_shell",
    "breakout",
]

[ch6_exercise]
cases = [
    "initproc",
    "user_shell",
    "breakout",
]
